//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fees
    {
        public fees()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int FID { get; set; }
        public string plan_name { get; set; }
        public Nullable<int> fee_amount { get; set; }
    
        public virtual ICollection<Student> Student { get; set; }
    }
}
