//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        public int Vid { get; set; }
        public string path { get; set; }
        public string description { get; set; }
        public Nullable<int> TID { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
